import {StyleSheet, Dimensions} from 'react-native';
import {scale, verticalScale, moderateScale} from '.././lib/scalingUtils';

const window = Dimensions.get('window');
export const colors = {
  white: '#ffffff',
  red_light: '#ff2e57',
  red_light_opacity: 'rgba(255, 46, 86, 0.2)',
  black_light: '#232323',
  black_light1: '#303030',
  black: '#000000',
  facebook_back: '#0288d1',
  grey: '#565656',
  brown: '#fd7042',
  bg_pink: '#e8c5d8',
  bg_grey: '#f4f4f4',
  bg_yellow: '#ffbb00',
  pink_light: '#ffe6eb',
  walk_child_back: '#144181',
  walk_preg_back: '#458f6d',
  walk_period_back: '#ff2e56',
  walk_period_top_back: '#365e8a',
  walk_discuss_back: '#35809c',
  walk_discuss_back_light: '#6bb5d1',
  walk_top_back: '#ffdcd4',
  walk_discuss_txt: '#253858',
  walk_discrptn_txt: '#f1f1f1',
  btn_back_color: '#ea7b88',
  back_gradient_top: '#ececec',
  back_gradient_bottom: '#f07a85',
  wecome_txt: '#022b3a',
  warm_grey_four: '#979797',
  pnkish: '#b650ef',
  txt_period: '#282828',
  gradient_header1: '#ff2d55',
  gradient_header2: '#ff598e',
  light_grey: '#a2abbf',
  indicator_back: '#f2f3f3',
  login_desc: '#565656',
  pinkish_grey: '#d0d0d0',
  warning_desc: '#878787',
  info_text: '#0288d1',
  walktrgh_arrow: '#222872',
  txt_report: '#3d3d3d',
  grey_popino: '#a8a8a8',
  txt_pregnant: '#98022b3a',
  txt_pregnant_ovulation: '#022b3a',
  txt_opansans: '#44566c',
  period_grey: '#a4a2a2',
  tnc_text_color: '#2d2d2d',
  login_text_color: '#080808',
  placeholder_color: '#a4a2a2',
  txt_header_color: '#d8557f',
  txt_pill_color: '#1f1f1f',
  txt_pill_name_color: '#696969',
  txt_user_name_color: '#333333',
  txt_health_color: '#4a4141',
  txt_height_color: '#151515',
  txt_calendar_day: '#rgba(0, 0, 0, 0)',
  txt_ovulation_color: '#756a6a',
  txt_week_name_color: '#2e343b',
  txt_week_disable_name_color: '#8d99a6',
  symptomes_svg_color: '#9CD5EC',
  intecourse_color: '#ec6233',
  light_pink: '#fceff6',
  grey_border_color: '#d1d1d1',
  yellow_text_color: '#ffbb00',
  blue_green: '#149ea3',
  light_green: '#dcfeff',
  seafoam_blue: '#75c7a0',
  yellow_color: '#fbd154',
};

export function Capitalize(str) {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

export const sizes = {
  listImageSize: moderateScale(60),
  headerHeight: moderateScale(50, 0.4),
  tabHeight: moderateScale(45, 0.4),
  floatingButton: moderateScale(50),
  profileImgBackgroundHeight: moderateScale(280),
  profileImgBackgroundWidth: window.width,
  titosIconSize: moderateScale(40, 0.8),
  btnSize: verticalScale(210),
};

export const colorTypes = {
  1: colors.white,
  2: colors.red_light,
  3: colors.black_light,
  4: colors.black_light1,
  5: colors.black,
  6: colors.grey,
  7: colors.brown,
  8: colors.walk_discuss_txt,
  9: colors.walk_discrptn_txt,
  10: colors.wecome_txt,
  11: colors.pnkish,
  12: colors.txt_period,
  13: colors.light_grey,
  14: colors.login_desc,
  15: colors.pinkish_grey,
  16: colors.warning_desc,
  17: colors.info_text,
  18: colors.txt_report,
  19: colors.grey_popino,
  20: colors.txt_pregnant,
  21: colors.txt_pregnant_ovulation,
  22: colors.txt_opansans,
  23: colors.period_grey,
  24: colors.walktrgh_arrow,
  25: colors.walk_period_back,
  26: colors.tnc_text_color,
  27: colors.login_text_color,
  28: colors.placeholder_color,
  29: colors.txt_header_color,
  30: colors.txt_pill_color,
  31: colors.txt_pill_name_color,
  32: colors.txt_user_name_color,
  33: colors.txt_health_color,
  34: colors.txt_height_color,
  35: colors.txt_calendar_day,
  36: colors.txt_ovulation_color,
  37: colors.txt_week_name_color,
  38: colors.txt_week_disable_name_color,
  39: colors.walk_discuss_back,
  40: colors.walk_discuss_back,
  41: colors.walk_preg_back,
  42: colors.yellow_text_color,
  43: colors.bg_pink,
  44: colors.walk_discuss_back_light,
  45: colors.seafoam_blue,
};

export const globalStyle = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.light_pink,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  bigCircle: {
    height: 80,
    width: 80,
    borderRadius: 80 / 2,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    shadowColor: '#ff2e56',
    backgroundColor: colors.white,
    shadowOpacity: 0.5,
    shadowRadius: 7,
    overflow: 'hidden',
    shadowOffset: {width: 0, height: 0},
  },
  bigCircle1: {
    alignItems: 'center',
    shadowColor: '#ff2e56',
    shadowOpacity: 0.5,
    shadowRadius: 7,
    shadowOffset: {width: 0, height: 0},
    height: moderateScale(80),
    width: moderateScale(80),
    borderRadius: moderateScale(80) / 2,
    backgroundColor: colors.white,
    alignSelf: 'center',
    opacity: 0.7,
    position: 'absolute',
  },
  weekSubView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#e8c5d8',
    width: moderateScale(92),
    height: moderateScale(31.5),
    borderTopLeftRadius: moderateScale(5),
    borderBottomLeftRadius: moderateScale(5),
    paddingLeft: moderateScale(15),
    paddingRight: moderateScale(5),
    alignSelf: 'center',
    marginRight: moderateScale(-2),
  },
  circleView: {
    width: moderateScale(16),
    height: moderateScale(16),
    backgroundColor: '#2d2d2d',
    borderRadius: moderateScale(8),
    alignItems: 'center',
    justifyContent: 'center',
  },
  weekMainView: {
    flexDirection: 'row',
    alignItems: 'center',
    alignContent: 'space-between',
  },
  dropDownStyle: {
    //height: moderateScale(200),
    width: moderateScale(100),
    paddingLeft: moderateScale(10),
    borderRadius: moderateScale(5),
    borderWidth: 1,
    //     position:"absolute",
    //     zIndex:1
  },
  textCenter: {
    textAlign: 'center',
  },
});
