export const NAVIGATION_NAVIGATE = 'Navigation/NAVIGATE';
export const NAVIGATION_RESET = 'Navigation/RESET';
export const NAVIGATION_BACK = 'Navigation/BACK';
export const LOGOUT_USER_RESET = 'LOGOUT_USER_RESET';
export const INITIATE_AUTH_STATE = 'INITIATE_AUTH_STATE';
export const INITIATE_AUTH_APP_STATE = 'INITIATE_AUTH_APP_STATE';
export const INITIATE_DEVICE_ID = 'INITIATE_DEVICE_ID';
export const SET_MENSTRUAL_GOAL = 'SET_MENSTRUAL_GOAL';
export const SHOW_HEADER_INFO_MODAL = 'SHOW_HEADER_INFO_MODAL';
export const HIDE_HEADER_INFO_MODAL = 'HIDE_HEADER_INFO_MODAL';
export const INITIATE_START_PERIOD_DATE = 'INITIATE_START_PERIOD_DATE';
export const INITIATE_END_PERIOD_DATE = 'INITIATE_END_PERIOD_DATE';
export const INITIATE_DELETE_DATE = 'INITIATE_DELETE_DATE';
export const INITIATE_MENSTRUAL_DATE = 'INITIATE_MENSTRUAL_DATE';
export const INITIATE_PERIOD_DAYS = 'INITIATE_PERIOD_DAYS';
export const INITIATE_PERIOD_DATE = 'INITIATE_PERIOD_DATE';
export const INITIATE_NEW_USER_DATA = 'INITIATE_NEW_USER_DATA';
export const INITIATE_OVULATION_DAYS = 'INITIATE_OVULATION_DAYS';
export const INITIATE_TWICE_DATE = 'INITIATE_TWICE_DATE';
export const DELETE_TWICE_DATE = 'DELETE_TWICE_DATE';
export const SAVE_TEMPERATURE_UNIT = 'SAVE_TEMPERATURE_UNIT';
export const SAVE_WEIGHT_HEIGHT_UNIT = 'SAVE_WEIGHT_HEIGHT_UNIT';
export const INITIATE_WEIGHT_ARRAY = 'INITIATE_WEIGHT_ARRAY';
export const SAVE_TEMPERATURE_DATA = 'SAVE_TEMPERATURE_DATA';
export const DELETE_TEMPERATURE_DATA = 'DELETE_TEMPERATURE_DATA';
export const SAVE_WEIGHT_DATA = 'SAVE_WEIGHT_DATA';
export const DELETE_WEIGHT_DATA = 'DELETE_WEIGHT_DATA';
export const SAVE_SYMPTOMS_DATA = 'SAVE_SYMPTOMS_DATA';
export const SAVE_MOODS_DATA = 'SAVE_MOODS_DATA';
export const SAVE_TEST_MONITORS = 'SAVE_TEST_MONITORS';
export const SAVE_VAGINAL_DISCHARGE_DATA = 'SAVE_VAGINAL_DISCHARGE_DATA';
export const SVAE_CONTACEPTIVE_PILL_DATA = 'SVAE_CONTACEPTIVE_PILL_DATA';
export const SAVE_PROTECTION_DATA = 'SAVE_PROTECTION_DATA';
export const SAVE_NOTES_DATA = 'SAVE_NOTES_DATA';
export const DELETE_NOTES_DATA = 'DELETE_NOTES_DATA';
export const SAVE_HEALTH_DATA = 'SAVE_HEALTH_DATA';
export const SAVE_OBSTETRICS_DATA = 'SAVE_OBSTETRICS_DATA';
export const SAVE_MED_HISTORY_DATA = 'SAVE_MED_HISTORY_DATA';
export const SAVE_BIRTH_CONTROL_DATA = 'SAVE_BIRTH_CONTROL_DATA';
export const SAVE_SUGAR_DATA = 'SAVE_SUGAR_DATA';
export const DELETE_SUGAR_DATA = 'DELETE_SUGAR_DATA';
export const SAVE_BLOOD_PRESSURE_DATA = 'SAVE_BLOOD_PRESSURE_DATA';
export const DELETE_BLOOD_PRESSURE_DATA = 'DELETE_BLOOD_PRESSURE_DATA';
export const SAVE_HEALTH_LOG_DATA = 'SAVE_HEALTH_LOG_DATA';
export const DELETE_HEALTH_LOG_DATA = 'DELETE_HEALTH_LOG_DATA';

export const ADD_PERIOD_DATA = 'ADD_PERIOD_DATA';
export const DELETE_PERIOD_DATA = 'DELETE_PERIOD_DATA';
export const MODIFY_PERIOD_DATA = 'MODIFY_PERIOD_DATA';
export const SAVE_PERIOD_DATA = 'SAVE_PERIOD_DATA';
export const SAVE_HEIGHT_DATA = 'SAVE_HEIGHT_DATA';
export const INITIATE_NOTES_DATE = 'INITIATE_NOTES_DATE';
//USER LOCATION
export const USER_LOCATION_PERMISSION = 'USER_LOCATION_PERMISSION';
//Notification
export const SAVE_NOTIFICATION_DATA = 'SAVE_NOTIFICATION_DATA';
export const INITIATE_NOTIFICATION_DATA = 'INITIATE_NOTIFICATION_DATA';
//Walthrought
export const WALTHROUGH_SKIP = 'WALTHROUGH_SKIP';

//Signup using device id
export const SIGNUP_DEVICE_REQUEST = 'SIGNUP_DEVICE_REQUEST';
export const SIGNUP_DEVICE_SUCCESS = 'SIGNUP_DEVICE_SUCCESS';
export const SIGNUP_DEVICE_FAILURE = 'SIGNUP_DEVICE_FAILURE';

//Signup using device id
export const DEREGISTER_DEVICE_REQUEST = 'DEREGISTER_DEVICE_REQUEST';
export const DEREGISTER_DEVICE_SUCCESS = 'DEREGISTER_DEVICE_SUCCESS';
export const DEREGISTER_DEVICE_FAILURE = 'DEREGISTER_DEVICE_FAILURE';

export const RESET_LOGOUT_STATE = 'RESET_LOGOUT_STATE';

export const LOGIN_FACEBOOK_REQUEST = 'LOGIN_FACEBOOK_REQUEST';
export const LOGIN_FACEBOOK_SUCCESS = 'LOGIN_FACEBOOK_SUCCESS';
export const LOGIN_FACEBOOK_FAILURE = 'LOGIN_FACEBOOK_FAILURE';

export const LOGIN_EMAIL_RESET = 'LOGIN_EMAIL_RESET';
export const LOGIN_EMAIL_REQUEST = 'LOGIN_EMAIL_REQUEST';
export const LOGIN_EMAIL_SUCCESS = 'LOGIN_EMAIL_SUCCESS';
export const LOGIN_EMAIL_FAILURE = 'LOGIN_EMAIL_FAILURE';
// Numer login
export const LOGIN_MOBILE_RESET = 'LOGIN_MOBILE_RESET';
export const LOGIN_MOBILE_REQUEST = 'LOGIN_MOBILE_REQUEST';
export const LOGIN_MOBILE_SUCCESS = 'LOGIN_MOBILE_SUCCESS';
export const LOGIN_MOBILE_FAILURE = 'LOGIN_MOBILE_FAILURE';
// verify numer otp
export const VERIFY_MOBILE_REQUEST = 'VERIFY_MOBILE_REQUEST';
export const VERIFY_MOBILE_SUCCESS = 'VERIFY_MOBILE_SUCCESS';
export const VERIFY_MOBILE_FAILURE = 'VERIFY_MOBILE_FAILURE';

export const VERIFY_EMAIL_REQUEST = 'VERIFY_EMAIL_REQUEST';
export const VERIFY_EMAIL_SUCCESS = 'VERIFY_EMAIL_SUCCESS';
export const VERIFY_EMAIL_FAILURE = 'VERIFY_EMAIL_FAILURE';
// Health sync
export const HEALTH_SYNC_REQUEST = 'HEALTH_SYNC_REQUEST';
export const HEALTH_SYNC_SUCCESS = 'HEALTH_SYNC_SUCCESS';
export const HEALTH_SYNC_FAILURE = 'HEALTH_SYNC_FAILURE';
//update profile picture
export const UPDATE_PROFILE_PICTURE_REQUEST = 'UPDATE_PROFILE_PICTURE_REQUEST';
export const UPDATE_PROFILE_PICTURE_SUCCESS = 'UPDATE_PROFILE_PICTURE_SUCCESS';
export const UPDATE_PROFILE_PICTURE_FAILURE = 'UPDATE_PROFILE_PICTURE_FAILURE';
//register device id
export const REGISTER_DEVICE_ID_REQUEST = 'REGISTER_DEVICE_ID_REQUEST';
export const REGISTER_DEVICE_ID_SUCCESS = 'REGISTER_DEVICE_ID_SUCCESS';
export const REGISTER_DEVICE_ID_FAILURE = 'REGISTER_DEVICE_ID_SUFAILURE';
//user info
export const USER_INFO_REQUEST = 'USER_INFO_REQUEST';
export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';
export const USER_INFO_FAILURE = 'USER_INFO_FAILURE';
//update name
export const UPDATE_NAME_REQUEST = 'UPDATE_NAME_REQUEST';
export const UPDATE_NAME_SUCCESS = 'UPDATE_NAME_SUCCESS';
export const UPDATE_NAME_FAILURE = 'UPDATE_NAME_FAILURE';
//update birthdate
export const UPDATE_BIRTHDATE_REQUEST = 'UPDATE_BIRTHDATE_REQUEST';
export const UPDATE_BIRTHDATE_SUCCESS = 'UPDATE_BIRTHDATE_SUCCESS';
export const UPDATE_BIRTHDATE_FAILURE = 'UPDATE_BIRTHDATE_FAILURE';
//update location
export const UPDATE_LOCATION_REQUEST = 'UPDATE_LOCATION_REQUEST';
export const UPDATE_LOCATION_SUCCESS = 'UPDATE_LOCATION_SUCCESS';
export const UPDATE_LOCATION_FAILURE = 'UPDATE_LOCATION_FAILURE';
//update profile
export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';
//save feedback
export const SAVE_FEEDBACK_REQUEST = 'SAVE_FEEDBACK_REQUEST';
export const SAVE_FEEDBACK_SUCCESS = 'SAVE_FEEDBACK_SUCCESS';
export const SAVE_FEEDBACK_FAILURE = 'SAVE_FEEDBACK_FAILURE';
